In [5]:
import pandas as pd

tabela = pd.read_csv("olist_customers_dataset.csv", sep=",")
display(tabela)

# Visualizando os primeiros registros
print("Primeiros registros da tabela:")
print(tabela.head())

# Ordenando os dados por uma coluna específica (por exemplo, 'category_name')
tabela_ordenada = tabela.sort_values(by='customer_city')

# Visualizando os primeiros registros após a ordenação
print("\nPrimeiros registros da tabela após ordenação:")
print(tabela_ordenada.head())

# Filtrando os dados (por exemplo, onde 'category_name' é igual a algum valor específico)
tabela_filtrada = tabela[tabela['customer_city'] == 'Cidade do Cliente']

# Visualizando os primeiros registros após a filtragem
print("\nPrimeiros registros da tabela após filtragem:")
print(tabela_filtrada.head())

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

Primeiros registros da tabela:
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

Primeiros registros da tabela após ordenação:
                            customer_id                customer_unique_id  \
44027  a23e3f9a2b656b23b7e52075964b42cd  afddf43a03a9941624ed42c0b2c17280
74529  9e01f714a2b3b8962c222cf2b74c20dc  e1feae9083c4c2895ddf6dc80526a85d
19445  f11eb8f0b8b87510a93e3e1aa10b0ade  64ee476500a01beb94df40f97a108c50
42307  576d71ddb21b21763cfedce73b902180  8d76b559181609308fcae630ea64cd61
5205   5e9e1ae42e02df93e9a591e86fd531a3  28af9604f7830ef6d1230fb575c39eb1

       customer_zip_code_prefix        customer_city customer_state
44027                     38540  abadia dos dourados             MG
74529                     38540  abadia dos dourados             MG
19445                     38540  abadia dos dourados             MG
42307                     72940            abadiania             GO
5205                      35620               abaete             MG

Primeiros registros da tabela após filtragem:
Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []